services:
  - type: web
    name: jackpot-pulse-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        value: YOUR_BOT_TOKEN_HERE
